### ISSUE TITLE
.csv Export Bugs

### ISSUE THREAD

**Issue by StefanMPopp** [mooch443/trex#59] opened 2021-06-03 16:45 UTC
These are not critical bugs and I could work around them, but I still wanted to make you aware of them.

- sometimes, an empty .csv file is exported (among others that are fine). It contains the headers but no data.
- sometimes, 2 additional, unspecified empty columns (no header, no data) are output in a .csv file (again, while most other files are fine).
For both issues I could not find an obvious pattern or trigger. "Sometimes" means in about 5% of the files.

Please let me know which additional information you need, if any.

**Comment by mooch443** [comment] 2021-06-07 14:38
1. I can imagine an empty CSV file being exported in case the individual does not exist, but is still listed internally (somehow, e.g. after reanalysis with track_max_individuals = 0 or some other "bug" like this). Did you check whether the mentioned individuals _should_ contain data, and which columns did you export? I mean, looking at the specific individual in the video - that would decide whether it is a mild or a bad output bug, or a (mild) bug in the tracking.
2. Hm. Where are these empty columns? Can you give a part of such a file, condensed down to one or two rows + header?

Thanks a bunch for all your reports, this is helpful!
-Tristan

**Comment by piotrvidal** [comment] 2022-02-04 03:57
I was checking today the export capabilities and couldn't reproduce this issue. I had to create some small snippet to combine all the .npz into a .csv, though, because I couldn't find a direct export functionality to .csv

Here's an output with a few rows and a header:
[test.npz_merged_data.csv](https://github.com/mooch443/trex/files/7999900/test.npz_merged_data.csv)

I had to omit the last two `npz[header]` too (`'frame_segments'` and `'segment_vxys'`) cause they had a different shape and wouldn't fit on the .csv. Maybe these are the columns that are empty? They contain data, but depending on how it's parsed LibreOffice or Excel won't show it or mess completely the format, I think.

Hope this helps!

**Comment by mooch443** [comment] 2022-02-26 19:41
Hard to say what caused it, but I also would not generally advise to convert from npz->csv directly. As you say - some of the shapes might be incompatible. The export to .csv (in case you haven't found a solution yet) is done via ``output_format = csv``. Although this is limited. ``frame_segments`` and such will not be exported this way, due to the exact issue that you described.

Honestly, I dislike csv - especially because of the large size of files and unflexibility - but I do understand that this may be easier to import into other programs (everyone supports plain-text), especially for smaller datasets. I will close this issue for now. Feel free to open a new one or reopen it/a discussion if you think this wasn't resolved.
Thanks! :-)

**Closed by mooch443** 2022-02-26 19:41 UTC
Labels: bug
