### ISSUE TITLE
Inf in data

### ISSUE THREAD

**Issue by roaldarbol** [mooch443/trex#21] opened 2021-03-11 15:47 UTC
**Describe the bug**
Getting on with the tracking, again, thanks for having made this! This issue is about the data output. After tracking, there's a few `Inf` observations. First of all, I'm not sure why they are there (I assume it's from frames where the animal wasn't tracked), and why it defaults to `Inf` rather than `NaN`. An undesired effect it has is that the observation that follows the `Inf`'s get much higher values, creating some serious outlier observations. For now, I'll just remove the affected observations, but just thought I bring up that it might not be the best default behaviour. 
For e.g. speeds or accelerations (anything derivative really), I'd think the best default would be to only supply values when there's actually two consecutive observations, and otherwise to `NaN`?

**Screenshots**
An example of this (don't mind the angles):
<img width="382" alt="Screenshot 2021-03-11 at 15 08 10" src="https://user-images.githubusercontent.com/25629697/110813154-239f4f80-8280-11eb-93ea-c657a278395e.png">

**Comment by mooch443** [comment] 2021-03-19 11:36
Hey!
`Inf` simply stands for "no data" and can be understood synonymously to `NaN`, so your assumption was correct. It is indeed a bit worrying that there seem to be outlier values _after_. Your best bet right now will be to remove them, yes, but I will investigate this. Thanks for pointing out!
-Tristan

**Comment by mooch443** [comment] 2021-03-25 20:29
The next release (v1.1.2) will add a new option `output_invalid_value` which can be set to `NaN`. This way, you'll be able to achieve the desired behaviour. I also fixed the issue that you pointed at with the large outlier values. This is fixed now - as intended previously, this uses the (correct) time since the individual was lost to when it was found again, to interpolate speed. You may be right that it is advisable to remove this first value in your analysis (if this is critical), but at least it won't add outliers anymore (at least according to my testing).

This issue will close with the release of the new version, thanks again for reporting this!

**Closed** 2021-03-26 09:24 UTC
Labels: bug
